/* =========================================================
   photos.js — 料理の写真（あれば写真、なければ dishes.js のイラストを表示）

   書き方（キーは data.js の art と同じ名前）:
     sushi: {
       file: 'photos/sushi.jpg',          // このフォルダからの相対パス
       credit: '撮影者名',                 // 画像の隅に表示
       license: 'CC BY-SA 4.0',           // 再配布できるライセンスのみ
       source: 'https://commons.wikimedia.org/wiki/File:....jpg'  // 出典（任意）
     },

   写真が読みこめなかったときは、自動でイラストにもどります。
   ========================================================= */
window.DISH_PHOTOS = {
  acai: { file: "photos/acai.jpg", credit: "Joe Crawford from San Diego, California, USA", license: "CC BY 2.0", source: "https://commons.wikimedia.org/wiki/File:A%C3%A7a%C3%AD_na_tigela_-_Acai_bowl.jpg" },
  ackee: { file: "photos/ackee.jpg", credit: "gailf548 from New York State, USA", license: "CC BY 2.0", source: "https://commons.wikimedia.org/wiki/File:Ackee_and_Saltfish.jpg" },
  adobo: { file: "photos/adobo.jpg", credit: "dbgg1979 on flickr", license: "CC BY 2.0", source: "https://commons.wikimedia.org/wiki/File:Chicken_adobo.jpg" },
  asado: { file: "photos/asado.jpg", credit: "felixion", license: "CC BY-SA 2.0", source: "https://commons.wikimedia.org/wiki/File:Asado_argentino_en_parrilla_a_carb%C3%B3n.jpg" },
  bacalhau: { file: "photos/bacalhau.jpg", credit: "Marek Ślusarczyk (Tupungato)", license: "CC BY 3.0", source: "https://commons.wikimedia.org/wiki/File:008_Bacalhau_com_natas_serving_in_a_restaurant_in_Coimbra,_Portugal_-_Portuguese_cuisine_dish.jpg" },
  banosh: { file: "photos/banosh.jpg", credit: "Galvm", license: "CC BY-SA 4.0", source: "https://commons.wikimedia.org/wiki/File:Banosh_in_restaurant_Bokorash-Kvasy_Rakhivskyi_Zakarpatska.jpg" },
  bicol: { file: "photos/bicol.jpg", credit: "Ymirazudis", license: "CC BY-SA 4.0", source: "https://commons.wikimedia.org/wiki/File:Bicol_Express_at_La_Herencia_Comida.jpg" },
  bobotie: { file: "photos/bobotie.jpg", credit: "CharmaineZoe's Marvelous Melange from England", license: "CC BY 2.0", source: "https://commons.wikimedia.org/wiki/File:Falmouth,_Cornwall_-_Bobotie_(Lightly_spiced_mutton,_almonds_and_raisins_with_a_baked_egg_and_cream_topping)_served_with_raisin_rice_and_chutney.jpg" },
  borscht: { file: "photos/borscht.jpg", credit: "liz west from Boxborough, MA", license: "CC BY 2.0", source: "https://commons.wikimedia.org/wiki/File:Borscht_served.jpg" },
  bouillabaisse: { file: "photos/bouillabaisse.jpg", credit: "Sergey A. Demidov", license: "CC BY 4.0", source: "https://commons.wikimedia.org/wiki/File:20250903_Bouillabaisse_in_Khimki_(90108).jpg" },
  buna: { file: "photos/buna.jpg", credit: "Miraethiopia", license: "CC BY-SA 4.0", source: "https://commons.wikimedia.org/wiki/File:Ethiopian_coffee_ceremony_jebena_and_finjan.jpg" },
  burger: { file: "photos/burger.jpg", credit: "Renee Comet (photographer)", license: "Public domain", source: "https://commons.wikimedia.org/wiki/File:Cheeseburger.jpg" },
  bushtucker: { file: "photos/bushtucker.jpg", credit: "JIP", license: "CC BY-SA 4.0", source: "https://commons.wikimedia.org/wiki/File:Kangaroo_steak_at_restaurant_BBQ_House.jpg" },
  buuz: { file: "photos/buuz.jpg", credit: "Mizu basyo", license: "CC BY-SA 3.0", source: "https://commons.wikimedia.org/wiki/File:Mongolian_buuz.jpg" },
  caolau: { file: "photos/caolau.jpg", credit: "avlxyz", license: "CC BY-SA 2.0", source: "https://commons.wikimedia.org/wiki/File:Cao_Lau_-_Ba_Be,_Hoi_An_Market_VND15000.jpg" },
  ceviche: { file: "photos/ceviche.jpg", credit: "MiguelAlanCS", license: "CC BY-SA 4.0", source: "https://commons.wikimedia.org/wiki/File:Ceviche_peruano.jpg" },
  chuno: { file: "photos/chuno.jpg", credit: "Eric in SF", license: "CC BY-SA 3.0", source: "https://commons.wikimedia.org/wiki/File:Chu%C3%B1o.jpg" },
  dakos: { file: "photos/dakos.jpg", credit: "Frente", license: "CC BY-SA 3.0", source: "https://commons.wikimedia.org/wiki/File:Koukouvagia.jpg" },
  dalbhat: { file: "photos/dalbhat.jpg", credit: "Gaurav Dhwaj Khadka", license: "CC BY-SA 4.0", source: "https://commons.wikimedia.org/wiki/File:Dal_Bhat_Tarkari_2.jpg" },
  dhido: { file: "photos/dhido.jpg", credit: "Janak Bhatta", license: "CC BY-SA 4.0", source: "https://commons.wikimedia.org/wiki/File:Nepali_Dhido.jpg" },
  dimsum: { file: "photos/dimsum.jpg", credit: "Mshuang2", license: "CC0", source: "https://commons.wikimedia.org/wiki/File:Three_dim_sum_in_steamer_basket.jpg" },
  dosa: { file: "photos/dosa.jpg", credit: "Marajozkee", license: "CC BY-SA 4.0", source: "https://commons.wikimedia.org/wiki/File:Masala_dosa_01.jpg" },
  feijoada: { file: "photos/feijoada.jpg", credit: "Bradleyzm", license: "CC BY-SA 4.0", source: "https://commons.wikimedia.org/wiki/File:Feijoada_%C3%A0_brasileira_-02.jpg" },
  finnbiff: { file: "photos/finnbiff.jpg", credit: "Htm", license: "Public domain", source: "https://commons.wikimedia.org/wiki/File:Poronk%C3%A4ristys.jpg" },
  fishchips: { file: "photos/fishchips.jpg", credit: "Grendelkhan", license: "CC BY-SA 4.0", source: "https://commons.wikimedia.org/wiki/File:Fish_and_chips_plate_with_peas.jpg" },
  fondue: { file: "photos/fondue.jpg", credit: "the_junes", license: "CC BY 2.0", source: "https://commons.wikimedia.org/wiki/File:Cheese_fondue-01-a.jpg" },
  galette: { file: "photos/galette.jpg", credit: "Arnaud 25", license: "CC BY-SA 4.0", source: "https://commons.wikimedia.org/wiki/File:Galette_de_sarrasin_compl%C3%A8te_bretonne.jpg" },
  gazpacho: { file: "photos/gazpacho.jpg", credit: "Bocadorada", license: "CC BY-SA 2.0", source: "https://commons.wikimedia.org/wiki/File:Gazpacho_Cazuela_Barro.jpg" },
  gravlaks: { file: "photos/gravlaks.jpg", credit: "Chris Olszewski", license: "CC BY-SA 4.0", source: "https://commons.wikimedia.org/wiki/File:Gravlax,_Christmas_Eve_dinner_in_Brisbane,_Australia,_2024.jpg" },
  gulyas: { file: "photos/gulyas.jpg", credit: "Lily15", license: "CC BY-SA 3.0", source: "https://commons.wikimedia.org/wiki/File:Gulyas080.jpg" },
  gumbo: { file: "photos/gumbo.jpg", credit: "Amadscientist", license: "CC BY-SA 3.0", source: "https://commons.wikimedia.org/wiki/File:Gumbo.JPG" },
  haggis: { file: "photos/haggis.jpg", credit: "Biology Big Brother", license: "CC BY 2.0", source: "https://commons.wikimedia.org/wiki/File:Haggis_neeps_and_tatties.jpg" },
  halaszle: { file: "photos/halaszle.jpg", credit: "János Korom Dr. from Wien, Austria", license: "CC BY-SA 2.0", source: "https://commons.wikimedia.org/wiki/File:Balatoni_hal%C3%A1szl%C3%A9_094_(4375940169).jpg" },
  hamsi: { file: "photos/hamsi.jpg", credit: "E4024", license: "CC BY-SA 4.0", source: "https://commons.wikimedia.org/wiki/File:Hamsi_tava,_roka,_lemon_and_red_onions.jpg" },
  hangi: { file: "photos/hangi.jpg", credit: "Sarah Stewart", license: "CC BY 2.0", source: "https://commons.wikimedia.org/wiki/File:EDC_hangi_2010.jpg" },
  houtou: { file: "photos/houtou.jpg", credit: "Jungle", license: "CC BY-SA 3.0", source: "https://commons.wikimedia.org/wiki/File:Houtou.jpg" },
  injera: { file: "photos/injera.jpg", credit: "Miguel Discart", license: "CC BY-SA 2.0", source: "https://commons.wikimedia.org/wiki/File:A_formal_serving_of_wat_atop_injera_in_Brussels,_Belgium.jpg" },
  ishikari: { file: "photos/ishikari.jpg", credit: "Adonis Chen from Hokkaido", license: "CC BY 2.0", source: "https://commons.wikimedia.org/wiki/File:Ishikari_nabe_by_Adonis_Chen_in_Hokkaido.jpg" },
  jeonbok: { file: "photos/jeonbok.jpg", credit: "bryan...", license: "CC BY-SA 2.0", source: "https://commons.wikimedia.org/wiki/File:Jeonbok-juk.jpg" },
  jerk: { file: "photos/jerk.jpg", credit: "Secretlondon", license: "CC BY-SA 3.0", source: "https://commons.wikimedia.org/wiki/File:Jerk_chicken_as_served_july_05.jpg" },
  jollof: { file: "photos/jollof.jpg", credit: "Segun Famisa", license: "CC BY-SA 4.0", source: "https://commons.wikimedia.org/wiki/File:Jollof_rice_with_vegetable.jpg" },
  kebab: { file: "photos/kebab.jpg", credit: "Maksym Kozlenko", license: "CC BY-SA 4.0", source: "https://commons.wikimedia.org/wiki/File:2023-01-20_Lamb_Shish_Kebab.jpg" },
  khaosoi: { file: "photos/khaosoi.jpg", credit: "Chainwit.", license: "CC BY-SA 4.0", source: "https://commons.wikimedia.org/wiki/File:Khao_Soi_Northern_Thai_food_%E0%B8%82%E0%B9%89%E0%B8%B2%E0%B8%A7%E0%B8%8B%E0%B8%AD%E0%B8%A2_%E0%B8%9C%E0%B8%B1%E0%B8%81%E0%B8%94%E0%B8%AD%E0%B8%87.jpg" },
  khorkhog: { file: "photos/khorkhog.jpg", credit: "Brücke-Osteuropa", license: "Public domain", source: "https://commons.wikimedia.org/wiki/File:Khorkhog_2.JPG" },
  kibbeh: { file: "photos/kibbeh.jpg", credit: "Bazel", license: "CC BY-SA 3.0", source: "https://commons.wikimedia.org/wiki/File:Kibbeh3.jpg" },
  kimchi: { file: "photos/kimchi.jpg", credit: "최광모", license: "CC BY-SA 4.0", source: "https://commons.wikimedia.org/wiki/File:Baechu_kimchi.jpg" },
  kokoda: { file: "photos/kokoda.jpg", credit: "yuko_ppp2501", license: "CC BY 2.0", source: "https://commons.wikimedia.org/wiki/File:Kokodafood.jpg" },
  koshari: { file: "photos/koshari.jpg", credit: "Dina Said", license: "CC BY-SA 4.0", source: "https://commons.wikimedia.org/wiki/File:Egyptian_food_Koshary.jpg" },
  lagman: { file: "photos/lagman.jpg", credit: "赤猫法師", license: "CC BY-SA 4.0", source: "https://commons.wikimedia.org/wiki/File:Uzbek_lagman.jpg" },
  lamb: { file: "photos/lamb.jpg", credit: "CNEcija12345", license: "CC BY-SA 4.0", source: "https://commons.wikimedia.org/wiki/File:Roast_leg_of_lamb.jpg" },
  locro: { file: "photos/locro.jpg", credit: "Diaz de vivar gustavo", license: "CC BY-SA 4.0", source: "https://commons.wikimedia.org/wiki/File:Locro_del_25_de_Mayo_Argentino.jpg" },
  lovo: { file: "photos/lovo.jpg", credit: "Jaejay77", license: "CC BY-SA 4.0", source: "https://commons.wikimedia.org/wiki/File:Lovo.jpg" },
  mapo: { file: "photos/mapo.jpg", credit: "Sichuanfoodlover", license: "CC BY-SA 4.0", source: "https://commons.wikimedia.org/wiki/File:Authentic_Mapo_Tofu.jpg" },
  meatpie: { file: "photos/meatpie.jpg", credit: "Finbar.concaig", license: "CC BY-SA 4.0", source: "https://commons.wikimedia.org/wiki/File:Aussie_meat_pie_(cropped).jpg" },
  mezze: { file: "photos/mezze.jpg", credit: "cyclonebill", license: "CC BY-SA 2.0", source: "https://commons.wikimedia.org/wiki/File:Flickr_-_cyclonebill_-_Tabbouleh.jpg" },
  moussaka: { file: "photos/moussaka.jpg", credit: "Andy Li", license: "CC0", source: "https://commons.wikimedia.org/wiki/File:Meat_Moussaka_-_Kouzina,_Brighton_2023-11-24.jpg" },
  oscypek: { file: "photos/oscypek.jpg", credit: "Pawel Swiegoda (Paberu)", license: "CC BY-SA 2.5", source: "https://commons.wikimedia.org/wiki/File:Oscypki.jpg" },
  paella: { file: "photos/paella.jpg", credit: "Jan Harenburg", license: "CC BY-SA 4.0", source: "https://commons.wikimedia.org/wiki/File:01_Paella_Valenciana_original.jpg" },
  palov: { file: "photos/palov.jpg", credit: "赤猫法師", license: "CC BY-SA 4.0", source: "https://commons.wikimedia.org/wiki/File:Uzbekistan_style_plov_in_Japan.jpg" },
  pap: { file: "photos/pap.jpg", credit: "Pietersielie(PC)", license: "CC BY-SA 4.0", source: "https://commons.wikimedia.org/wiki/File:Pap_with_sheba,_wors_and_mutton_chop.jpg" },
  papeda: { file: "photos/papeda.jpg", credit: "Gunawan Kartapranata", license: "CC BY-SA 3.0", source: "https://commons.wikimedia.org/wiki/File:Papeda,_Kuah_Kuning,_Ikan_Tude_Bakar_2.jpg" },
  peking: { file: "photos/peking.jpg", credit: "joyosity", license: "CC BY 2.0", source: "https://commons.wikimedia.org/wiki/File:Peking_duck_wrap_1.jpg" },
  pelmeni: { file: "photos/pelmeni.jpg", credit: "Eugene Kim @ Flickr", license: "CC BY 2.0", source: "https://commons.wikimedia.org/wiki/File:Pelmeni_Russian.jpg" },
  perche: { file: "photos/perche.jpg", credit: "PetOtools", license: "CC BY-SA 4.0", source: "https://commons.wikimedia.org/wiki/File:Filet_de_perche_meuniere_nov_2020.jpg" },
  pho: { file: "photos/pho.jpg", credit: "Andy Li", license: "CC0", source: "https://commons.wikimedia.org/wiki/File:Pho_Bo_by_Banh_%26_Mee_in_Kirkgate_Market.jpg" },
  pibil: { file: "photos/pibil.jpg", credit: "Popo le Chien", license: "CC BY-SA 3.0", source: "https://commons.wikimedia.org/wiki/File:Cochinita_pibil_2.jpg" },
  pierogi: { file: "photos/pierogi.jpg", credit: "MOs810", license: "CC BY-SA 4.0", source: "https://commons.wikimedia.org/wiki/File:Pierogi_ruskie,_Nowe_Warpno.jpg" },
  pilau: { file: "photos/pilau.jpg", credit: "Cmwaura", license: "CC BY-SA 4.0", source: "https://commons.wikimedia.org/wiki/File:Pilau_Food_in_Kenya.jpg" },
  pizza: { file: "photos/pizza.jpg", credit: "Mario56", license: "CC BY-SA 3.0", source: "https://commons.wikimedia.org/wiki/File:Margherita_Originale.JPG" },
  plankedsalmon: { file: "photos/plankedsalmon.jpg", credit: "Sharon Chen from Austin, United States", license: "CC BY 2.0", source: "https://commons.wikimedia.org/wiki/File:Cedar_Plank_Salmon_with_Peach_Pico_De_Gallo_3_(28791094630).jpg" },
  porco: { file: "photos/porco.jpg", credit: "Rui Ornelas", license: "CC BY 2.0", source: "https://commons.wikimedia.org/wiki/File:Carne_de_porco_%C3%A0_Alentejana.jpg" },
  poutine: { file: "photos/poutine.jpg", credit: "Antonydstevens", license: "CC0", source: "https://commons.wikimedia.org/wiki/File:Poutine_from_Windsor,_ON.jpg" },
  rendang: { file: "photos/rendang.jpg", credit: "GeeJo", license: "CC BY-SA 2.0", source: "https://commons.wikimedia.org/wiki/File:Lamb_rendang.jpg" },
  risotto: { file: "photos/risotto.jpg", credit: "Number55", license: "CC BY-SA 3.0", source: "https://commons.wikimedia.org/wiki/File:Risotto_alla_Milanese.JPG" },
  sardine: { file: "photos/sardine.jpg", credit: "Yusuke Kawasaki from Tokyo, Japan", license: "CC BY 2.0", source: "https://commons.wikimedia.org/wiki/File:Grilled_Sardines_5.50%E2%82%AC_Marisqueira_O_Varino_Nazar%C3%A9_(3785526688).jpg" },
  sayadeya: { file: "photos/sayadeya.jpg", credit: "young shanahan", license: "CC BY 2.0", source: "https://commons.wikimedia.org/wiki/File:Fish_Sayadieh.jpg" },
  spatzle: { file: "photos/spatzle.jpg", credit: "Takeaway", license: "CC BY-SA 4.0", source: "https://commons.wikimedia.org/wiki/File:2015_0718_K%C3%A4sesp%C3%A4tzle_S%C3%B6lden.jpg" },
  stroganina: { file: "photos/stroganina.jpg", credit: "Cholbon", license: "CC BY-SA 4.0", source: "https://commons.wikimedia.org/wiki/File:Dish_Stroganina_.jpg" },
  sushi: { file: "photos/sushi.jpg", credit: "Tim Reckmann from Hamm, Deutschland", license: "CC BY 2.0", source: "https://commons.wikimedia.org/wiki/File:Nigiri_Sushi_(25966163204).jpg" },
  suya: { file: "photos/suya.jpg", credit: "WhisperToMe", license: "CC0", source: "https://commons.wikimedia.org/wiki/File:SuyavarietiesTX.JPG" },
  tacos: { file: "photos/tacos.jpg", credit: "T.Tseng", license: "CC BY 2.0", source: "https://commons.wikimedia.org/wiki/File:Tacos_al_pastor,_taco_de_panza.jpg" },
  tagine: { file: "photos/tagine.jpg", credit: "Marco Almbauer", license: "CC BY-SA 4.0", source: "https://commons.wikimedia.org/wiki/File:Moroccan_tajine_with_meat.jpg" },
  thali: { file: "photos/thali.jpg", credit: "Kanikatwl", license: "CC BY-SA 4.0", source: "https://commons.wikimedia.org/wiki/File:North_indian_thali_at_a_restaurant.jpg" },
  thieb: { file: "photos/thieb.jpg", credit: "KVDP", license: "Public domain", source: "https://commons.wikimedia.org/wiki/File:Thieboudienne.JPG" },
  thiere: { file: "photos/thiere.jpg", credit: "Cheikh cherif", license: "CC BY-SA 4.0", source: "https://commons.wikimedia.org/wiki/File:Couscous_de_mil_(thi%C3%A9r%C3%A9).jpg" },
  tomyum: { file: "photos/tomyum.jpg", credit: "Andy Li", license: "CC0", source: "https://commons.wikimedia.org/wiki/File:Tom_Yum_Goong_Noodle_Soup_-_Nok_Nok_Kitchen_at_The_Cow_2024-03-28.jpg" },
  ugali: { file: "photos/ugali.jpg", credit: "Catherine Amia", license: "CC BY-SA 4.0", source: "https://commons.wikimedia.org/wiki/File:Posho_(Ugali),_Sukuma_wiki_%2B_kale.jpg" },
  wurst: { file: "photos/wurst.jpg", credit: "Benreis", license: "CC BY 3.0", source: "https://commons.wikimedia.org/wiki/File:Bratwurst_Sauerkraut_Becher_Br%C3%A4u_Bayreuth.JPG" },
};
